name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      
      - name: Build Summary
        run: zig build -Doptimize=ReleaseSafe -fsummary -freference-trace

      - name: Download test model (Windows)
        if: startsWith(matrix.runs-on, 'windows')
        run: ./models/download-ggml-model.cmd base.en
      - name: Download test model (Linux)
        if: startsWith(matrix.runs-on, 'ubuntu')
        run: bash ./models/download-ggml-model.sh base.en
      - name: Download test model (MacOS)
        if: startsWith(matrix.runs-on, 'macos')
        run: bash ./models/download-ggml-model.sh base.en
      
      - name: Build Test
        run: zig build whisper -Doptimize=ReleaseSafe -- -m models/ggml-base.en.bin -f samples/jfk.wav


  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - run: zig fmt --check --ast-check **.zig
